# fo_companies.py

fo_companies = [
    "RELIANCE INDUSTRIES LTD",
    "TATA CONSULTANCY SERVICES LTD",
    "INFOSYS LTD",
    "ICICI BANK LTD",
    "ADANI PORTS AND SPECIAL ECONOMIC ZONE LTD",
    "HDFC BANK LTD",
    "HCL TECHNOLOGIES LTD",
    "LARSEN & TOUBRO LTD",
    "KOTAK MAHINDRA BANK LTD",
    "YES BANK LTD",
    "GENSOL ENGINEERING LTD",
    "ZEE ENTERTAINMENT ENTERPRISES LTD",
    "SREI INFRASTRUCTURE FINANCE LTD",
    "VODAFONE IDEA LTD"
]
